---
title: "USA Rezessionswahrscheinlichkeit"
author: "Philipp Hauber"
date: "2 12 2019"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=6, #fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
# clear workspace
rm(list = ls())

# turn off scientific notation
options(scipen = 999)

# working directory
setwd("C:/Users/Philipp/Documents/GitHub/US-term-spread-rec-prob")
#setwd("C:/Users/Hauber/Documents/GitHub/US-term-spread-rec-prob")

# libraries
library(fredr)
library(purrr)
library(ggplot2)
library(tidyr)
library(dplyr)
library(lubridate)
library(pROC)

# set API key for FRED
fredr_set_key("84efd638e2db29ef758e0d8e081a4c05")
```


# Motivation

# Literatur

# Daten

```{r}
# load yield curve data, recession indicator and Fed Board term premium from FRED #################
var_mnemonic <- c("USREC", "GS10", "TB3MS", "THREEFYTP10")
var_names <- c("nber_rec", "i10y", "i3m", "tp_board")
data_fred <- data.frame()
for (i in 1 : length(var_names)) {
    tmp <- fredr(series_id = var_mnemonic[i], 
                                 observation_start = as.Date("1950-01-01"),
                                 frequency = "m", 
                                 aggregation_method = "avg"
                 )
    
    tmp[, "series_id"] <- var_names[i]
    
    data_fred <- rbind(data_fred, tmp)
}


# load term spread data from NY Fed ################
data_nyfed_raw <- read.table("ACMTermPremium.csv", 
                   header = TRUE, 
                   sep = ";", 
                   blank.lines.skip = FALSE)

data_nyfed_raw$DATE <- dmy(data_nyfed_raw$DATE)

# select term premium on 10 year bond
data_nyfed <- data_nyfed_raw %>% rename(date = DATE, tp_d = ACMTP10) %>%
                            select(date, tp_d) %>% 
                            mutate(yy = year(date), mm = month(date)) %>%
                            group_by(yy, mm) %>%
                            summarise(tp_ny = round(mean(tp_d),2)) %>%
                            ungroup() %>% 
                            mutate(date = make_date(year = yy, month = mm)) %>%
                            select(-yy, -mm) %>%
                            select(date, tp_ny)

# merge two datasets and create term-premium adjusted spread ########
dataM <- merge(spread(data_fred, series_id, value), data_nyfed, by = "date") %>% 
                mutate(i10y_tp_ny = i10y - tp_ny,
                       spr = i10y - i3m,
                       spr_tp = i10y - tp_ny - i3m) %>%
                gather(variable, value, -date)

# convert to quarterly frequency
dataQ <- dataM %>% filter(variable %in% c("i10y", "i3m", "nber_rec", "tp_ny")) %>%
                   mutate(yy = year(date), qq = ceiling(month(date) / 3)) %>%
                   group_by(variable, yy, qq) %>%
                   summarise(value = mean(value)) %>%
                   ungroup() %>% 
                   mutate(date = make_date(year = yy, month = 3 * qq - 2)) %>%
                   select(-yy, -qq) %>% 
                   select(date, everything()) %>% 
                   spread(variable, value) %>% 
                   mutate(spr = i10y - i3m, 
                          spr_tp = i10y - tp_ny - i3m,
                          nber_rec_tmp = ceiling(nber_rec)) %>% 
                   select(-nber_rec) %>% 
                   rename(nber_rec = nber_rec_tmp) %>% 
                   gather(variable, value, -date)

# different recession definition t : t+3
tmp <- dataQ %>% spread(variable, value) %>%
                 select(date, nber_rec) %>%
                 mutate(lead1 = lead(nber_rec, 1),
                        lead2 = lead(nber_rec, 2),
                        lead3 = lead(nber_rec, 3)
                        )

tmp2 <- as.matrix(select(tmp, -date))
tmp3 <- matrix(0, nrow(tmp2), 1)
tmp3[apply(tmp2 == 1, c(1), any)] <- 1

dataQ <- rbind(dataQ, data.frame(variable = "nber_rec2", value = tmp3, date = tmp$date)) 

# dataframe with start and end of recession => used for recession shading
data_tmp <- dataM %>% filter(variable == "nber_rec") %>% 
                     mutate(ind_rec_start = lag(value) == 0 & value == 1,
                            ind_rec_end = lag(value) == 1 & value == 0) %>%
                     filter(ind_rec_start == TRUE | ind_rec_end == TRUE) 

df_recM <- data.frame(start =  data_tmp$date[data_tmp$ind_rec_start == TRUE],
                     end = data_tmp$date[data_tmp$ind_rec_end == TRUE])

df_recM <- df_recM %>% mutate(end2 = end %m-% months(1)) %>% 
                     select(start, end2) %>% 
                     rename(end = end2) 

data_tmp <- dataQ %>% filter(variable == "nber_rec") %>% 
                     mutate(ind_rec_start = lag(value) == 0 & value == 1,
                            ind_rec_end = lag(value) == 1 & value == 0) %>%
                     filter(ind_rec_start == TRUE | ind_rec_end == TRUE) 

df_recQ <- data.frame(start =  data_tmp$date[data_tmp$ind_rec_start == TRUE],
                     end = data_tmp$date[data_tmp$ind_rec_end == TRUE])

df_recQ <- df_recQ %>% mutate(end2 = end %m-% months(3)) %>% 
                     select(start, end2) %>% 
                     rename(end = end2) 
```

## Zinsstrukturkurve

```{r}
dataM %>% filter(variable %in% c("i10y", "i3m")) %>%
         ggplot()+
         geom_line(aes(x = date, y = value, group = variable, col = variable))+
         theme_bw()+
         geom_rect(data = df_recM, 
                   aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),
                  fill='grey', alpha=0.4
                  )
```

## Laufzeitprämien

```{r}
dataM %>% filter(variable %in% c("tp_ny", "tp_board")) %>%
         ggplot()+
         geom_line(aes(x = date, y = value, group = variable, col = variable))+
         theme_bw()+
         geom_rect(data = df_recM, 
                   aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),
                  fill='grey', alpha=0.4
                  )
```


```{r}
Nh <- 4
data_tmp <- 

# add rows 
data_add <- data.frame(date = seq(from = dataQ$date[nrow(dataQ)] %m+% months(3), 
                                  by = "quarters", 
                                  length.out = Nh
                                  ),
                       spr = rep(NA, Nh),
                       tp_ny = rep(NA, Nh),
                       nber_rec = rep(NA, Nh),
                       nber_rec2 = rep(NA, Nh)
                       )

data_tmp <- dataQ %>% filter(variable %in% c("nber_rec", "nber_rec2", "spr", "tp_ny")) %>%
                      spread(variable, value) %>%
                      rbind(data_add) %>% 
                      filter(date >= "1972-01-01") %>%
                      mutate(lag_spr = lag(spr, Nh),
                            lag_tp_ny = lag(tp_ny, Nh),
                            trend = c(1 : n()),
                            lag_spr_tp = lag_spr - lag_tp_ny)

data_estim <- data_tmp %>% filter(date <= "2007-12-01")

zk <- glm(nber_rec ~ lag_spr, 
                family = binomial(link = "probit"), 
                data = data_estim)
zk_tp <- glm(nber_rec ~ lag_spr_tp, 
                family = binomial(link = "probit"), 
                data = data_estim)

zk_tp_t <- glm(nber_rec ~ lag_spr_tp + trend, 
                family = binomial(link = "probit"), 
                data = data_estim)

zk_tp_t2 <- glm(nber_rec ~ lag_spr_tp + I(trend ^ 2), 
                family = binomial(link = "probit"), 
                data = data_estim)

data.frame(date = data_tmp$date, 
           zk = predict(zk, data_tmp, type = "response"),
           zk_tp = predict(zk_tp, data_tmp, type = "response"),
           zk_tp_t = predict(zk_tp_t, data_tmp, type = "response"),
           zk_tp_t2 = predict(zk_tp_t2, data_tmp, type = "response")
           ) %>%
    gather(model, value, -date) %>%
    ggplot()+ 
        geom_line(aes(x = date, y = value, group = model, color = model))+
        theme_bw()+
        geom_rect(data = filter(df_recQ, start >= "1972-01-01"),
                  aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),
                  fill='grey', alpha=0.4
                 )
```

# Schätzung

## Probit-Modelle

Zwei Spezifikationen

- **ZK** (Zinstrukturkurve)
$$Pr(rec_{t+h} = 1 | \mathcal{I}_t) = \Phi(\alpha_0 + \alpha_1 \, spread_{t})$$

-  **ZK_TP** (Zinsstrukturkurve + Laufzeitprämie)
$$rec_{t+h} = \alpha_0 + \alpha_1 (spread_{t} - tp_t) + e_t$$

## Set-up

```{r, echo = TRUE}
Nh_q <- 4 # forecast horizon in quarters
Nh_m <- 12 # forecast horizon in months
sample_start <- "1972-01-01"
eval_start <- "1985-01-01"
eval_end <- "2017-10-01"
```

## Ergebnisse

```{r}
f_forecast_loop_probit <- function(data, eval_start, eval_end, freq, Nh){
    df_fore <- data.frame()

    for (date_eval in seq(from = as.Date(eval_start), to = as.Date(eval_end), by = freq))  {
        # data 
        data_tmp <- data %>% filter(variable %in% c("nber_rec", "nber_rec2","spr", "spr_tp", "tp_ny"),
                                    date <= date_eval, date > sample_start) %>%
                                select(date, variable, value) %>%
                                spread(variable, value) %>%
                                mutate(lag_spr = lag(spr, Nh),
                                       lag_spr_tp = lag(spr_tp, Nh),
                                       lag_tp = lag(tp_ny, Nh),
                                       trend = 1 : n()
                                       )
        
        data_estim <- data_tmp %>% filter(date < date_eval)
        data_eval <- data_tmp %>% filter(date == date_eval)
        
        # models
        zk <- glm(nber_rec ~ lag_spr, 
                        family = binomial(link = "probit"), 
                        data = data_estim)
    
        zk_tp <- glm(nber_rec ~ lag_spr_tp, 
                            family = binomial(link = "probit"), 
                            data = data_estim)
        
        zk_tp_t <- glm(nber_rec ~ lag_spr_tp + trend, 
                            family = binomial(link = "probit"), 
                            data = data_estim)
        
        zk_tp_t2 <- glm(nber_rec ~ lag_spr_tp + I(trend ^ 2), 
                    family = binomial(link = "probit"), 
                    data = data_estim)
        
        # forecasts
        df_fore <- rbind(df_fore,
                           data.frame(zk = round(predict(zk, data_eval, type = "response"), 3),
                                      zk_tp = round(predict(zk_tp, data_eval, type = "response"), 3),
                                      zk_tp_t = round(predict(zk_tp_t, data_eval, type = "response"), 3),
                                      zk_tp_t2 = round(predict(zk_tp_t2, data_eval, type = "response"), 3),
                                      actual = data_eval$nber_rec,
                                      date = data_eval$date)
                           )
    }
    return(df_fore)
}
```


### Quartalsdaten

```{r}
df_foreQ <- f_forecast_loop_probit(dataQ, eval_start, eval_end, "quarters", Nh_q)

# plot predicted recession probabilites and recession shading
df_foreQ %>% select(-actual) %>%
            gather(model, value, -date) %>% 
            ggplot()+
            geom_line(aes(x = date, y = value, group = model, col = model)) +
            ylim(0,1)+
            theme_bw()+
            geom_rect(data = filter(df_recQ, start >= eval_start, start <= eval_end, 
                                    end >= eval_start, end <= eval_end),
                      aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),
                      fill='grey', alpha=0.4
                     )
```

## Monatsdaten

```{r}
df_foreM <- f_forecast_loop_probit(dataM, eval_start, eval_end, "months", Nh_m)

# plot predicted recession probabilites and recession shading
df_foreM %>% select(-actual) %>%
            gather(model, value, -date) %>% 
            ggplot()+
            geom_line(aes(x = date, y = value, group = model, col = model)) +
            ylim(0,1)+
            theme_bw()+
            geom_rect(data = filter(df_recM, start >= eval_start, start <= eval_end, 
                                    end >= eval_start, end <= eval_end),
                      aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),
                      fill='grey', alpha=0.4
                     )
```


# Evaluierung

## ROC-Kurve

### Quartalsdaten

```{r}
roc_zk <- roc(df_foreQ, actual, zk,
              ret = c("roc", "coords", "all_coords"))

roc_zk_tp <- roc(df_foreQ, actual, zk_tp,
                 ret = c("roc", "coords", "all_coords"))

roc_zk_tp_t <- roc(df_foreQ, actual, zk_tp_t,
                   ret = c("roc", "coords", "all_coords"))

roc_zk_tp_t2 <- roc(df_foreQ, actual, zk_tp_t2,
                   ret = c("roc", "coords", "all_coords"))

ggroc(list(zk = roc_zk, zk_tp = roc_zk_tp, zk_tp_t = roc_zk_tp_t, zk_tp_t2 = roc_zk_tp_t2), legacy.axes = TRUE)
```

### Monatsdaten

```{r}
roc_zk <- roc(df_foreM, actual, zk,
              ret = c("roc", "coords", "all_coords"))

roc_zk_tp <- roc(df_foreM, actual, zk_tp,
                 ret = c("roc", "coords", "all_coords"))

roc_zk_tp_t <- roc(df_foreM, actual, zk_tp_t,
                   ret = c("roc", "coords", "all_coords"))

roc_zk_tp_t2 <- roc(df_foreM, actual, zk_tp_t2,
                   ret = c("roc", "coords", "all_coords"))

ggroc(list(zk = roc_zk, zk_tp = roc_zk_tp, zk_tp_t = roc_zk_tp_t, zk_tp_t2 = roc_zk_tp_t2), legacy.axes = TRUE)
```

